const healthLabels = [
  // "alcohol-cocktail",
  "alcohol-free",
  // "celery-free",
  // "crustacean-free",
  // "dairy-free",
  "DASH",
  // "egg-free",
  // "fish-free",
  // "fodmap-free",
  // "gluten-free",
  // "immuno-supportive",
  "keto-friendly",
  "kidney-friendly",
  // "kosher",
  "low-potassium",
  "low-sugar",
  // "lupine-free",
  "Mediterranean",
  "mollusk-free",
  // "mustard-free",
  "no-oil-added",
  "paleo",
  // "peanut-free",
  "pecatarian",
  "pork-free",
  "red-meat-free",
  // "sesame-free",
  // "shellfish-free",
  // "soy-free",
  "sugar-conscious",
  "sulfite-free",
  // "tree-nut-free",
  "vegan",
  "vegetarian",
  // "wheat-free"
];

const allergyLabels = [
  "celery-free",
  "crustacean-free",
  "dairy-free",
  "egg-free",
  "fish-free",
  "fodmap-free",
  "gluten-free",
  "immuno-supportive",
  "lupine-free",
  "mustard-free",
  "peanut-free",
  "sesame-free",
  "shellfish-free",
  "soy-free",
  "tree-nut-free",
  "wheat-free"
];

const cuisineTypes = [ //counts as a health label in the API
  "american",
  "asian",
  "british",
  "caribbean",
  "central europe",
  "chinese",
  "eastern europe",
  "french",
  "greek",
  "indian",
  "italian",
  "japanese",
  "korean",
  "kosher",
  "mediterranean",
  "mexican",
  "middle eastern",
  "nordic",
  "south american",
  "south east asian",
  "world"
];

const dishTypes = [
  "alcohol cocktail",
  "biscuits and cookies",
  "bread",
  "cereals",
  "condiments and sauces",
  "desserts",
  "drinks",
  "egg",
  "ice cream and custard",
  "main course",
  "pancake",
  "pasta",
  "pastry",
  "pies and tarts",
  "pizza",
  "preps",
  "preserve",
  "salad",
  "sandwiches",
  "seafood",
  "side dish",
  "soup",
  "special occasions",
  "starter",
  "sweets"
];

const mealTypes = [
  "breakfast",
  // "brunch",
  "lunch",
  "dinner",
  // "snack",
  // "teatime"
];

export { healthLabels, allergyLabels, cuisineTypes, dishTypes, mealTypes };